In [2]:
import numpy as np

In [4]:
#Create a null vector of size 10 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#Create a vector with values ranging from 10 to 49
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#Find the shape of previous array in question 3
np.shape(x)

(40,)

In [19]:
#Print the type of the previous array in question 3
type(x)

numpy.ndarray

In [13]:
 np.__version__ 

'1.19.4'

In [85]:
#dimension of array
x.ndim

2

In [18]:
#Create a boolean array with all the True values
np.array(range(1,10),dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [22]:
#Create a two dimensional array
np.array(range(9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
#Create a three dimensional array
np.array(range(24)).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
#Reverse a vector (first element becomes last)
np.flip(x,axis=None)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [32]:
#Create a null vector of size 10 but the fifth value which is 1
x=np.zeros(10,dtype=int)
x[5]=1
print(x)

[0 0 0 0 0 1 0 0 0 0]


In [33]:
#Create a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#Convert the data type of the given array from int to float
arr = np.array([1, 2, 3, 4, 5])
arrfloat=arr.astype(np.float64)
print(arrfloat)

[1. 2. 3. 4. 5.]


In [35]:
 #Multiply arr1 with arr2
 arr1 = np.array([[1., 2., 3.],
                [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
              [7., 2., 12.]])

np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [36]:
#Make an array by comparing both the arrays provided above
comparison= arr1==arr2
print(comparison)

[[False False False]
 [False False False]]


In [38]:
#odd numbers
x=np.array(range(10))
x[x % 2 == 1]


array([1, 3, 5, 7, 9])

In [40]:
#Replace all odd numbers to -1 from previous array
x[x % 2 == 1]=-1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [46]:
#Replace the values of indexes 5,6,7 and 8 to 12
for a in [5,6,7,8]:
  x[a]=12
print(x)

[ 0 -1  2 -1  4 12 12 12 12 -1]


In [49]:
#Create a 2d array with 1 on the border and 0 inside
x=np.zeros(9).reshape(3,3)
x[0,0]=1
#x[2,2]=1
print(x)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


difficulty level medium

In [52]:
#Replace the value 5 to 12
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#Convert all the values of 1st array to 64
arr3d[0,0]=64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [59]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
x=np.array(range(9)).reshape(3,3)
x[0]

array([0, 1, 2])

In [60]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
x[2,2]

8

In [62]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
x[0:2,2:3]

array([[2],
       [5]])

In [68]:
#Create a 10x10 array with random values and find the minimum and maximum values
y=np.array(range(100)).reshape(10,10)
print(np.amin(y, axis=None)) #minimum value
print(np.amax(y))

0
99


In [72]:
#Find the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [75]:
#Find the positions where elements of a and b match
np.intersect1d(a,b,return_indices=True)


(array([2, 4]), array([1, 5]), array([1, 5]))

In [111]:
#Find all the values from array data where the values from array names are not equal to Will
import random
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randint(7, size=random.randrange(1,10))
print(np.where(names[data]!="Will"))

(array([0]),)


In [112]:
#Find all the values from array data where the values from array names are not equal to Will and Joe
data = np.random.randint(7, size=random.randrange(1,10))
print(np.where(names[data]!="Will") and np.where(names[data]!="Joe") )

(array([0, 2]),)


**DIFFICULTY LEVEL HARD**

In [80]:
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [81]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16
np.arange(1,17).reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [84]:
#Swap axes of the array you created in Question 32
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [88]:
#Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
x=np.array(range(10))
x**1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [92]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
import random
a=np.random.randint(12,size=random.randrange(0,12))
b=np.random.randint(12,size=random.randrange(0,12))
np.where(a==b)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """


(array([], dtype=int64),)

In [93]:
#Find the unique names and sort them out
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [95]:
#From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)


array([1, 2, 3, 4])

In [99]:
#Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[1]=newColumn
print(sampleArray)

[[34 43 73]
 [10 10 10]
 [53 94 66]]


In [100]:
#Find the dot product of the above two matrix
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [103]:
#Generate a matrix of 20 random values and find its cumulative sum
m=np.random.randint(20,size=(random.randint(0,5),random.randint(0,5)))
np.cumsum(m)

array([ 13,  32,  45,  46,  56,  75,  82,  82,  89,  98, 114, 115])